apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-profile-service
  template:
    metadata:
      labels:
        app: user-profile-service
    spec:
      containers:
      - name: user-profile-service
        image: user-profile-service:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
spec:
  selector:
    app: user-profile-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
